name: API Test Automation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      petstore:
        image: swaggerapi/petstore
        ports:
          - 8080:8080
        options: >-
          --health-cmd="curl -f http://localhost:8080/api/v3/openapi.json"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test with Maven
        run: mvn clean test
        env:
          BASE_URL: http://localhost:8080/api/v3
