version: '3.8'

services:
  petstore:
    image: swaggerapi/petstore
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v3/openapi.json"]
      interval: 10s
      retries: 5

  api-tests:
    build: .
    depends_on:
      petstore:
        condition: service_healthy
    environment:
      BASE_URL: http://petstore:8080/api/v3
