version: '3.8'

services:
  petstore:
    image: swaggerapi/petstore3:1.0.16
    ports:
      - "8080:8080"
    networks:
      - testnet

  api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - petstore
    environment:
      - BASE_URL=http://petstore:8080
    networks:
      - testnet
    volumes:
      - ./test-output:/app/test-output

networks:
  testnet:
